/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Jogo.Jogo;
import Jogo.Posicao;
import javax.swing.JOptionPane;


/**
 *
 * @author guita
 */
public class Tela extends javax.swing.JFrame {
    //Peca[][] tabuleiro = new Peca[3][3];
    Jogo jogo = new Jogo(3,3);
    Posicao vazio = new Posicao();
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        this.setLocationRelativeTo(null);
        vazio = jogo.novoJogo();
        PovoarLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt01 = new javax.swing.JLabel();
        txt02 = new javax.swing.JLabel();
        txt10 = new javax.swing.JLabel();
        txt11 = new javax.swing.JLabel();
        txt12 = new javax.swing.JLabel();
        txt00 = new javax.swing.JLabel();
        txt20 = new javax.swing.JLabel();
        txt22 = new javax.swing.JLabel();
        txt21 = new javax.swing.JLabel();
        btnNovoJogo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt01.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        txt01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt01.setText("2");
        txt01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt01MouseClicked(evt);
            }
        });

        txt02.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        txt02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt02.setText("3");
        txt02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt02MouseClicked(evt);
            }
        });

        txt10.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        txt10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt10.setText("4");
        txt10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt10MouseClicked(evt);
            }
        });

        txt11.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        txt11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt11.setText("5");
        txt11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt11MouseClicked(evt);
            }
        });

        txt12.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        txt12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt12.setText("6");
        txt12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt12MouseClicked(evt);
            }
        });

        txt00.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        txt00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt00.setText("1");
        txt00.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt00MouseClicked(evt);
            }
        });

        txt20.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        txt20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt20.setText("7");
        txt20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt20MouseClicked(evt);
            }
        });

        txt22.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        txt22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt22.setText("0");
        txt22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt22MouseClicked(evt);
            }
        });

        txt21.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        txt21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt21.setText("8");
        txt21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt21MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt00, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt01, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt02, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt21, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt22, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt00, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt01, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt02, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt21, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt22, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btnNovoJogo.setText("Novo Jogo");
        btnNovoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoJogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btnNovoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNovoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt12MouseClicked
        // TODO add your handling code here:
        vazio = jogo.mover(vazio,Integer.parseInt(txt12.getText().equals("") ? "0":txt12.getText()));
        PovoarLabel();
    }//GEN-LAST:event_txt12MouseClicked

    private void txt22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt22MouseClicked
        // TODO add your handling code here:
        vazio = jogo.mover(vazio,Integer.parseInt(txt22.getText().equals("") ? "0":txt22.getText()));
        PovoarLabel();
    }//GEN-LAST:event_txt22MouseClicked

    private void txt02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt02MouseClicked
        // TODO add your handling code here:
        vazio = jogo.mover(vazio,Integer.parseInt(txt02.getText().equals("") ? "0":txt02.getText()));
        PovoarLabel();
    }//GEN-LAST:event_txt02MouseClicked

    private void txt21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt21MouseClicked
        // TODO add your handling code here:
        vazio = jogo.mover(vazio,Integer.parseInt(txt21.getText().equals("") ? "0":txt21.getText()));
        PovoarLabel();
    }//GEN-LAST:event_txt21MouseClicked

    private void txt11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt11MouseClicked
        // TODO add your handling code here:
        vazio = jogo.mover(vazio,Integer.parseInt(txt11.getText().equals("") ? "0":txt11.getText()));
        PovoarLabel();
    }//GEN-LAST:event_txt11MouseClicked

    private void txt01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt01MouseClicked
        // TODO add your handling code here:
        vazio = jogo.mover(vazio,Integer.parseInt(txt01.getText().equals("") ? "0":txt01.getText()));
        PovoarLabel();
    }//GEN-LAST:event_txt01MouseClicked

    private void txt20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt20MouseClicked
        // TODO add your handling code here:
        vazio = jogo.mover(vazio,Integer.parseInt(txt20.getText().equals("") ? "0":txt20.getText()));
        PovoarLabel();
    }//GEN-LAST:event_txt20MouseClicked

    private void txt10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt10MouseClicked
        // TODO add your handling code here:
        vazio = jogo.mover(vazio,Integer.parseInt(txt10.getText().equals("") ? "0":txt10.getText()));
        PovoarLabel();
    }//GEN-LAST:event_txt10MouseClicked

    private void txt00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt00MouseClicked
        // TODO add your handling code here:
        vazio = jogo.mover(vazio,Integer.parseInt(txt00.getText().equals("") ? "0":txt00.getText()));
        PovoarLabel();
    }//GEN-LAST:event_txt00MouseClicked

    private void btnNovoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoJogoActionPerformed
        // TODO add your handling code here:
        vazio = jogo.novoJogo();
        PovoarLabel();
    }//GEN-LAST:event_btnNovoJogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovoJogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt00;
    private javax.swing.JLabel txt01;
    private javax.swing.JLabel txt02;
    private javax.swing.JLabel txt10;
    private javax.swing.JLabel txt11;
    private javax.swing.JLabel txt12;
    private javax.swing.JLabel txt20;
    private javax.swing.JLabel txt21;
    private javax.swing.JLabel txt22;
    // End of variables declaration//GEN-END:variables


    private void PovoarLabel() {
         try{
             for(int x = 0; x < jogo.getTabuleiro().length ; x++){
                 for(int y = 0; y < jogo.getTabuleiro().length; y++){
                     int px = jogo.getTabuleiro()[x][y].getPosicaoX();
                     int py = jogo.getTabuleiro()[x][y].getPosicaoY();
                     
                     String s = "txt"+px+py;
                     
                     switch(s){
                         case "txt00":
                             txt00.setText(jogo.getTabuleiro()[x][y].getNumero() == 0 ? "" : String.valueOf(jogo.getTabuleiro()[x][y].getNumero()));
                             break;
                         case "txt01":
                             txt01.setText(jogo.getTabuleiro()[x][y].getNumero() == 0 ? "" : String.valueOf(jogo.getTabuleiro()[x][y].getNumero()));
                             break;
                         case "txt02":
                             txt02.setText(jogo.getTabuleiro()[x][y].getNumero() == 0 ? "" : String.valueOf(jogo.getTabuleiro()[x][y].getNumero()));
                             break;              
                         case "txt10":
                             txt10.setText(jogo.getTabuleiro()[x][y].getNumero() == 0 ? "" : String.valueOf(jogo.getTabuleiro()[x][y].getNumero()));
                             break;   
                         case "txt11":
                              txt11.setText(jogo.getTabuleiro()[x][y].getNumero() == 0 ? "" : String.valueOf(jogo.getTabuleiro()[x][y].getNumero()));
                             break;
                         case "txt12":
                             txt12.setText(jogo.getTabuleiro()[x][y].getNumero() == 0 ? "" : String.valueOf(jogo.getTabuleiro()[x][y].getNumero()));
                             break;
                         case "txt20":
                             txt20.setText(jogo.getTabuleiro()[x][y].getNumero() == 0 ? "" : String.valueOf(jogo.getTabuleiro()[x][y].getNumero()));
                             break;
                         case "txt21":
                             txt21.setText(jogo.getTabuleiro()[x][y].getNumero() == 0 ? "" : String.valueOf(jogo.getTabuleiro()[x][y].getNumero()));
                             break;
                         case "txt22":                        
                             txt22.setText(jogo.getTabuleiro()[x][y].getNumero() == 0 ? "" : String.valueOf(jogo.getTabuleiro()[x][y].getNumero()));
                             break;
                     }
                 }
             }
             
             if(jogo.getGanhou()){
                 JOptionPane.showMessageDialog(null, "PARABÉNS, VOCÊ GANHOU O JOGO!!!!");
                 
             }
         }catch(Exception er){
             throw er;
         }
    }
}
